version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projects
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/projects
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/projects
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
      SONAR_LOGIN: ${SONAR_LOGIN}
    depends_on:
      - db

volumes:
  postgres-data:
    driver: bridge