CREATE TABLE IF NOT EXISTS projects (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  manager VARCHAR(255) NOT NULL,
  forecast TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  budget NUMERIC(12,2) NOT NULL,
  description VARCHAR(500) NOT NULL,
  status BIGINT DEFAULT NULL
);